# Generated by Django 5.2.6 on 2025-09-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
