# Generated by Django 5.2.6 on 2025-09-11 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_email_verified_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("VENDOR", "Vendor"),
                    ("SUPPLIER", "Supplier"),
                ],
                default="CUSTOMER",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "search_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("search_count", models.IntegerField(default=1)),
                ("search_frequency", models.IntegerField(default=1)),
                ("last_searched", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
