# Generated by Django 5.2.6 on 2025-09-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SupportTicket",
        ),
    ]
