CREATE_PRODUCT_SUCCESS = "Product created successfully"
PRODUCT_NOT_FOUND = "Product with id '{}' not found"
PRODUCT_FEATURED_MAXIMUM_REACHED = (
    "Maximum number of {} featured products for seller reached"
)
MINIMUM_PRODUCT_REQUIRED = "A minimum of {} products is required to feature a product."
UPDATE_PRODUCT_SUCCESS = "Product updated successfully"
DELETE_PRODUCT_SUCCESS = "Product deleted successfully"
PRODUCT_DELETE_ERROR = "An error occurred while deleting the product. {}"
PRODUCT_NOT_AVAILABLE = "This product is not available for offers."
SELF_OFFER_ERROR = "You cannot make an offer on your own product."
OFFER_SUCCESS = "Offer created successfully"
OFFER_ALREADY_EXISTS = "You have already made an offer on this product."
OFFER_ACCEPTED = "Offer accepted successfully"
OFFER_REJECTED = "Offer rejected successfully"
COUNTER_OFFER_SUCCESS = "Counter offer created successfully"
OFFER_EXPIRED = "Offer with id '{}' has expired"
OFFER_ALREADY_ACCEPTED = "Offer with id '{}' has already been accepted"
OFFER_NOT_FOUND = "Offer with id '{}' not found"
UNAUTHORIZED = "You are not authorized to perform this action."
PRODUCT_REPORTED = "Product reported successfully."
ORDER_DOES_NOT_EXIST = "Order with id '{}' does not exist."
SELLER_RESPONSE_SUCCESS = "Seller's response successfully saved."
BRAND_NOT_FOUND = "Brand with id {} not found"
