name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: ${{ secrets.DEBUG }}
          envkey_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          envkey_ALLOW_LOGIN_NOT_VERIFIED: ${{ secrets.ALLOW_LOGIN_NOT_VERIFIED }}

          envkey_MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
          envkey_MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}

          envkey_TERMII_API_KEY: ${{ secrets.TERMII_API_KEY }}
          envkey_TERMII_SMS_URL: ${{ secrets.TERMII_SMS_URL }}
          envkey_TERMII_SENDER_ID: ${{ secrets.TERMII_SENDER_ID }}

          file_name: .env
          fail_on_empty: false

      - name: Build Docker images
        run: |
          docker compose build --force-rm --no-cache

  run:
    runs-on: self-hosted

    needs:
      - build

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Run Docker images
        run: |
          docker compose stop
          docker compose up -d --force-recreate --remove-orphans
          docker system prune --force
