# Generated by Django 5.2.6 on 2025-09-11 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "size_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MEN", "Men Sizes"),
                            ("WOMEN", "Women Sizes"),
                            ("KIDS", "Kids Sizes"),
                            ("TODDLERS", "Toddlers 2-5 years"),
                            ("UNISEX", "Unisex Sizes"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "size_subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLOTHING", "Clothing"),
                            ("SHOES", "Shoes"),
                            ("ACCESSORIES", "Accessories"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("Workwear", "Workwear"),
                            ("Workout", "Workout"),
                            ("Casual", "Casual"),
                            ("Party Dress", "Party Dress"),
                            ("Party Outfit", "Party Outfit"),
                            ("Formal Wear", "Formal Wear"),
                            ("Evening Wear", "Evening Wear"),
                            ("Wedding Guest", "Wedding Guest"),
                            ("Loungewear", "Loungewear"),
                            ("Vacation/Resort Wear", "Vacation/Resort Wear"),
                            ("Festival Wear", "Festival Wear"),
                            ("Activewear", "Activewear"),
                            ("Nightwear", "Nightwear"),
                            ("Vintage", "Vintage"),
                            ("Y2K", "Y2K"),
                            ("Boho", "Boho"),
                            ("Minimalist", "Minimalist"),
                            ("Grunge", "Grunge"),
                            ("Chic", "Chic"),
                            ("Streetwear", "Streetwear"),
                            ("Preppy", "Preppy"),
                            ("Retro", "Retro"),
                            ("Cottagecore", "Cottagecore"),
                            ("Glam", "Glam"),
                            ("Summer Styles", "Summer Styles"),
                            ("Winter Essentials", "Winter Essentials"),
                            ("Spring Florals", "Spring Florals"),
                            ("Autumn Layers", "Autumn Layers"),
                            ("Rainy Day Wear", "Rainy Day Wear"),
                            ("Denim & Jeans", "Denim & Jeans"),
                            ("Dresses & Gowns", "Dresses & Gowns"),
                            ("Jackets & Coats", "Jackets & Coats"),
                            ("Knitwear & Sweaters", "Knitwear & Sweaters"),
                            ("Skirts & Shorts", "Skirts & Shorts"),
                            ("Suits & Blazers", "Suits & Blazers"),
                            ("Tops & Blouses", "Tops & Blouses"),
                            ("Shoes & Footwear", "Shoes & Footwear"),
                            ("Travel-Friendly", "Travel-Friendly"),
                            ("Maternity Wear", "Maternity Wear"),
                            ("Athleisure", "Athleisure"),
                            ("Eco-Friendly/Upcycled", "Eco-Friendly/Upcycled"),
                            ("Festival-Ready", "Festival-Ready"),
                            ("Date Night", "Date Night"),
                            ("Ethnic Wear", "Ethnic Wear"),
                            ("Office Party Outfit", "Office Party Outfit"),
                            ("Cocktail Attire", "Cocktail Attire"),
                            ("Prom Dresses", "Prom Dresses"),
                            ("Music Concert Wear", "Music Concert Wear"),
                            ("Oversized", "Oversized"),
                            ("Slim Fit", "Slim Fit"),
                            ("Relaxed Fit", "Relaxed Fit"),
                            ("Christmas", "Christmas"),
                            ("School Uniforms", "School Uniforms"),
                        ],
                        default="Party Outfit",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("banner_url", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Workwear", "Workwear"),
                            ("Workout", "Workout"),
                            ("Casual", "Casual"),
                            ("Party Dress", "Party Dress"),
                            ("Party Outfit", "Party Outfit"),
                            ("Formal Wear", "Formal Wear"),
                            ("Evening Wear", "Evening Wear"),
                            ("Wedding Guest", "Wedding Guest"),
                            ("Loungewear", "Loungewear"),
                            ("Vacation/Resort Wear", "Vacation/Resort Wear"),
                            ("Festival Wear", "Festival Wear"),
                            ("Activewear", "Activewear"),
                            ("Nightwear", "Nightwear"),
                            ("Vintage", "Vintage"),
                            ("Y2K", "Y2K"),
                            ("Boho", "Boho"),
                            ("Minimalist", "Minimalist"),
                            ("Grunge", "Grunge"),
                            ("Chic", "Chic"),
                            ("Streetwear", "Streetwear"),
                            ("Preppy", "Preppy"),
                            ("Retro", "Retro"),
                            ("Cottagecore", "Cottagecore"),
                            ("Glam", "Glam"),
                            ("Summer Styles", "Summer Styles"),
                            ("Winter Essentials", "Winter Essentials"),
                            ("Spring Florals", "Spring Florals"),
                            ("Autumn Layers", "Autumn Layers"),
                            ("Rainy Day Wear", "Rainy Day Wear"),
                            ("Denim & Jeans", "Denim & Jeans"),
                            ("Dresses & Gowns", "Dresses & Gowns"),
                            ("Jackets & Coats", "Jackets & Coats"),
                            ("Knitwear & Sweaters", "Knitwear & Sweaters"),
                            ("Skirts & Shorts", "Skirts & Shorts"),
                            ("Suits & Blazers", "Suits & Blazers"),
                            ("Tops & Blouses", "Tops & Blouses"),
                            ("Shoes & Footwear", "Shoes & Footwear"),
                            ("Travel-Friendly", "Travel-Friendly"),
                            ("Maternity Wear", "Maternity Wear"),
                            ("Athleisure", "Athleisure"),
                            ("Eco-Friendly/Upcycled", "Eco-Friendly/Upcycled"),
                            ("Festival-Ready", "Festival-Ready"),
                            ("Date Night", "Date Night"),
                            ("Ethnic Wear", "Ethnic Wear"),
                            ("Office Party Outfit", "Office Party Outfit"),
                            ("Cocktail Attire", "Cocktail Attire"),
                            ("Prom Dresses", "Prom Dresses"),
                            ("Music Concert Wear", "Music Concert Wear"),
                            ("Oversized", "Oversized"),
                            ("Slim Fit", "Slim Fit"),
                            ("Relaxed Fit", "Relaxed Fit"),
                            ("Christmas", "Christmas"),
                            ("School Uniforms", "School Uniforms"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "parcel_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SMALL", "Small"),
                            ("MEDIUM", "Medium"),
                            ("LARGE", "Large"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Brand New with Tags", "Brand New with Tags"),
                            ("Brand New without Tags", "Brand New without Tags"),
                            ("Excellent Condition", "Excellent Condition"),
                            ("Good Condition", "Good Condition"),
                            ("Heavily Used", "Heavily Used"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("views", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                (
                    "discount_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("images_url", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("INACTIVE", "INACTIVE"),
                            ("SOLD", "SOLD"),
                            ("FLAGGED", "FLAGGED"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("color", models.JSONField(default=list)),
                (
                    "custom_brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("hashtags", models.JSONField(blank=True, default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
                (
                    "materials",
                    models.ManyToManyField(
                        blank=True,
                        related_name="material_products",
                        to="products.material",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.size",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "viewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecentlyViewedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
                "unique_together": {("user", "product")},
            },
        ),
    ]
