# Generated by Django 5.2.6 on 2025-09-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
